#!/usr/bin/env bash
# Prints best school many 10 times

count=1

while [ $count -le 10 ]
do
	if [ $count -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
		((count++))
	fi
		echo "Best School"
		((count++))
done
